#################################################
# DO Community Playbooks: Initial Server Setup
#################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install Prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

# Sudo Group Setup
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

# User + Key Setup
    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ create_user }}"
        state: present
        groups: wheel
        append: true
        create_home: true
        shell: /bin/bash

    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ copy_local_key }}"

# TODO(bowei): copy over root auth keys into new user
# TODO(bowei): run ssh-keygen as new user and add yourself to auth keys (necessary to ssh into self)

    - name: Disable ssh for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Reload ssh service
      service: name=ssh state=reloaded

# Install Packages
    - name: Update apt
      apt: update_cache=yes

    - name: Install required system packages
      apt: name={{ sys_packages }} state=latest

# Setup vnc server
    - name: Copy VNC service file, optional
      copy: src=files/vncserver@.service dest=/etc/systemd/system/vncserver@.service owner=root group=root mode=0644

    - name: Create vnc dir
      file:
        path: ~/.vnc
        mode: 0755
        state: directory

    - name: Create vnc dir
      file:
        path: ~/.vnc
        mode: 0755
        state: directory
      vars:
        ansible_become: false
      
    - name: Generate random passwd
      shell: |
        head -c8 /dev/urandom | md5sum | head -c8 | vncpasswd -f > ~/.vnc/passwd

    - name: Generate random passwd
      shell: |
        head -c8 /dev/urandom | md5sum | head -c8 | vncpasswd -f > ~/.vnc/passwd
      vars:
        ansible_become: false

    - name: Update file perms
      file:
        path: ~/.vnc/passwd
        mode: 0600

    - name: Update file perms
      file:
        path: ~/.vnc/passwd
        mode: 0600
      vars:
        ansible_become: false

    - name: Copy VNC startup script
      copy: src=files/xstartup dest=~/.vnc/xstartup mode=0644

    - name: Copy VNC startup script
      copy: src=files/xstartup dest=~/.vnc/xstartup mode=0644
      vars:
        ansible_become: false

    - name: Reload vnc service
      service: name=vncserver@1 state=reloaded

# UFW Setup
    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Deny all other incoming traffic by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming
