---
create_user: bowei
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw', 'ubuntu-gnome-desktop', 'tigervnc-standalone-server', 'python3-venv', 'wireguard', 'build-essential', 'zlib1g-dev', 'libffi-dev', 'python3.9-dev', 'openjdk-11-jdk', 'postgresql']
