---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
# repo-specific stuff
    - name: Cargo install wasm pack
      community.general.cargo:
        name: wasm-pack
      vars:
        ansible_become_user: "{{ create_user }}"
          # delete this

    - name: Create code dir
      ansible.builtin.file:
        path: /home/{{ create_user }}/code
        state: directory
        mode: '0755'
      vars:
        ansible_become_user: "{{ create_user }}"
          # git

    - name: Add a setting to ~/.gitconfig
      community.general.git_config:
        name: user.email
        scope: global
        value: liubowei@gmail.com
      vars:
        ansible_become_user: "{{ create_user }}"
    
    - name: Add a setting to ~/.gitconfig
      community.general.git_config:
        name: user.name
        scope: global
        value: Bowei Liu
      vars:
        ansible_become_user: "{{ create_user }}"

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/boweiliu/wasm-game-of-life.git'
        dest: /home/{{ create_user }}/code/wasm-game-of-life
      vars:
        ansible_become_user: "{{ create_user }}"

    - name: Git checkout this
      ansible.builtin.git:
        repo: 'https://github.com/boweiliu/ansible-playbooks.git'
        dest: /home/{{ create_user }}/code/ansible-playbooks
      vars:
        ansible_become_user: "{{ create_user }}"

